from crawler.amazon import review_extract
from crawler.amazon.questions_extract import get_questions

p = open("/Users/architdwivedi/Documents/a.csv").read().split("\n")[:-1]

ar = [
    ["https://www.amazon.com/dp/B00CX3ASFE", "Benefiber"],
    ["https://www.amazon.com/dp/B015VBRIXE", "Benefiber"],
    ["https://www.amazon.com/dp/B077RG1DDY", "Benefiber"],
    ["https://www.amazon.com/dp/B0091FABUE", "Kirkland Signature"],
    ["https://www.amazon.com/dp/B000MM2RZM", "Benefiber"],
    ["https://www.amazon.com/dp/B01KJ8TKEO", "Benefiber"],
    ["https://www.amazon.com/dp/B01IAIN72G", "Benefiber"],
    ["https://www.amazon.com/dp/B00XFFR0ZK", "Benefiber"],
    ["https://www.amazon.com/dp/B01978FIZC", "Benefiber"],
    ["https://www.amazon.com/dp/B00ZQUDM1I", "Benefiber"],
    ["https://www.amazon.com/dp/B00U0K6YMS", "Benefiber"],
    ["https://www.amazon.com/dp/B000KF861U", "Benefiber"],
    ["https://www.amazon.com/dp/B01CAXK25M", "Benefiber"],
    ["https://www.amazon.com/dp/B00CX3ASFO", "Benefiber"],
    ["https://www.amazon.com/dp/B00YDEP8RO", "Benefiber"],
    ["https://www.amazon.com/dp/B01MTPCPLS", "Miralax"],
    ["https://www.amazon.com/dp/B003CT2YQY", "Metamucil"],
    ["https://www.amazon.com/dp/B0013OW2KS", "NOW Foods"],
    ["https://www.amazon.com/dp/B07L5VRVLV", ""],
    ["https://www.amazon.com/dp/B004H2YFKI", "Garden of Life"],
    ["https://www.amazon.com/dp/B004H2YFKI", "Garden of Life"],
    ["https://www.amazon.com/dp/B01C8BR83A", "Culturelle"],
    ["https://www.amazon.com/dp/B015X2CGSS", "Benefiber"],
    ["https://www.amazon.com/dp/B074TZL3MK", "Benefiber"],
    ["https://www.amazon.com/dp/B004RFF630", "Citrucel"],
    ["https://www.amazon.com/dp/B01IAILP7A", "Benefiber"],
    ["https://www.amazon.com/dp/B00IMMPHZG", "Benefiber"],
    ["https://www.amazon.com/dp/B004QHLDOK", "Vitafusion"],
    ["https://www.amazon.com/dp/B01CZ5GTZC", "Benifiber"],
    ["https://www.amazon.com/dp/B001TH7K0G", "Metamucil"],
    ["https://www.amazon.com/dp/B00Y98KB6C", "Benefiber"],
    ["https://www.amazon.com/dp/B077FGC1F1", ""],
    ["https://www.amazon.com/dp/B0000VLWZQ", "Fibercon"],
    ["https://www.amazon.com/dp/B07JW6FJBZ", ""],
    ["https://www.amazon.com/dp/B00GYHWJRA", "Tomorrow's Nutrition"],
    ["https://www.amazon.com/dp/B01M2D8I02", ""],
    ["https://www.amazon.com/dp/B0077SXI7A", "Kirkland Signature"],
    ["https://www.amazon.com/dp/B0026JM6N2", ""],
    ["https://www.amazon.com/dp/B0129RR1D0", "NutriONN"],
    ["https://www.amazon.com/dp/B00CX3ASG8", "Benefiber"],
    ["https://www.amazon.com/dp/B01M1P8RUY", "Benefiber"],
    ["https://www.amazon.com/dp/B00AYJAPDO", "FiberAdvance"],
    ["https://www.amazon.com/dp/B07HGQT21H", "Melinda"],
    ["https://www.amazon.com/dp/B01AFQAA8K", ""],
    ["https://www.amazon.com/dp/B01M5GQPLD", "Phillips'"],
    ["https://www.amazon.com/dp/B00O2VQJSA", "Nature Made"],
    ["https://www.amazon.com/dp/B01M0M4WC0", "Benefiber"],
    ["https://www.amazon.com/dp/B0013U052Y", "Equate"],
    ["https://www.amazon.com/dp/B002NPCML0", "Vitafusion"],
    ["https://www.amazon.com/dp/B0792NZ28X", "Benefiber"],
    ["https://www.amazon.com/dp/B007SYT7LO", "Garden of Life"],
    ["https://www.amazon.com/dp/B00323NW5C", "Garden of Life"],
    ["https://www.amazon.com/dp/B01N7DTD98", "Garden of Life"],
    ["https://www.amazon.com/dp/B01NA7VLNL", "Garden of Life"],
    ["https://www.amazon.com/dp/B000GWKA2U", "Garden of Life"],
    ["https://www.amazon.com/dp/B00280M13Y", "Garden of Life"],
    ["https://www.amazon.com/dp/B00Y8MP4G6", "Garden of Life"],
    ["https://www.amazon.com/dp/B00K5NEPHG", "Garden of Life"],
    ["https://www.amazon.com/dp/B01A9IFE8K", "Garden of Life"],
    ["https://www.amazon.com/dp/B01N65M4ZB", "Garden of Life"],
    ["https://www.amazon.com/dp/B000GWG8FS", "Garden of Life"],
    ["https://www.amazon.com/dp/B01LQEMAJM", "Garden of Life"],
    ["https://www.amazon.com/dp/B00K5NEMJM", "Garden of Life"],
    ["https://www.amazon.com/dp/B005JAT318", "Garden of Life"],
    ["https://www.amazon.com/dp/B00K5NELJS", "Garden of Life"],
    ["https://www.amazon.com/dp/B01N9CTJET", "Garden of Life"],
    ["https://www.amazon.com/dp/B00K5NELNE", "Garden of Life"],
    ["https://www.amazon.com/dp/B00FB1S988", "Garden of Life"],
    ["https://www.amazon.com/dp/B01N9D5NB6", "Garden of Life"],
    ["https://www.amazon.com/dp/B003L31NM2", "Garden of Life"],
    ["https://www.amazon.com/dp/B002HI1LSI", "Garden of Life"],
    ["https://www.amazon.com/dp/B01LVYJK6U", "Garden of Life"],
    ["https://www.amazon.com/dp/B00R06N6DK", "Garden of Life"],
    ["https://www.amazon.com/dp/B001TH7K0G", "Metamucil"],
    ["https://www.amazon.com/dp/B001N0LPIC", "Metamucil"],
    ["https://www.amazon.com/dp/B0039283FU", "Metamucil"],
    ["https://www.amazon.com/dp/B06W2PJCVP", "Metamucil"],
    ["https://www.amazon.com/dp/B001G7QVAY", "Metamucil"],
    ["https://www.amazon.com/dp/B001GCTTK8", "Metamucil"],
    ["https://www.amazon.com/dp/B0013OW2KS", "NOW Foods"],
    ["https://www.amazon.com/dp/B0013I1H9G", "Metamucil"],
    ["https://www.amazon.com/dp/B000GG1Y7G", "Metamucil"],
    ["https://www.amazon.com/dp/B006TGVASK", ""],
    ["https://www.amazon.com/dp/B0013I4WJS", "Metamucil"],
    ["https://www.amazon.com/dp/B01N4L4D7H", "Metamucil"],
    ["https://www.amazon.com/dp/B01BS52GXE", "Metamucil"],
    ["https://www.amazon.com/dp/B00CX3ASFE", "Benefiber"],
    ["https://www.amazon.com/dp/B0013HX164", "Metamucil"],
    ["https://www.amazon.com/dp/B06WVKL6CR", "Metamucil"],
    ["https://www.amazon.com/dp/B01IPNOHUM", "Metamucil"],
    ["https://www.amazon.com/dp/B00CM98T7S", "Metamucil"],
    ["https://www.amazon.com/dp/B0013U052Y", "Equate"],
    ["https://www.amazon.com/dp/B007P4VNUK", "Metamucil"],
    ["https://www.amazon.com/dp/B0062NSWB8", "Metamucil"],
    ["https://www.amazon.com/dp/B0015EGWMU", "Metamucil"],
    ["https://www.amazon.com/dp/B01IAI1EAI", "Metamucil"],
    ["https://www.amazon.com/dp/B01KCJ8I1Q", "Metamucil"],
    ["https://www.amazon.com/dp/B01MTPCPLS", "Miralax"],
    ["https://www.amazon.com/dp/B01N9692HZ", "Metamucil"],
    ["https://www.amazon.com/dp/B079JKPWGW", "Metamucil"],
    ["https://www.amazon.com/dp/B0013I4WLG", "Metamucil"],
    ["https://www.amazon.com/dp/B001V9OMH6", "Metamucil"],
    ["https://www.amazon.com/dp/B00EEELBSI", "Metamucil"],
    ["https://www.amazon.com/dp/B00BNWSHV8", "Metamucil"],
    ["https://www.amazon.com/dp/B01CLIZGYI", "Metamucil"],
    ["https://www.amazon.com/dp/B001G7QVPE", "Metamucil"],
    ["https://www.amazon.com/dp/B001H9X8IY", "Metamucil"],
    ["https://www.amazon.com/dp/B01CLIZH9C", "Metamucil"],
    ["https://www.amazon.com/dp/B00G4EM9PA", "Metamucil"],
    ["https://www.amazon.com/dp/B01F803620", "Metamucil"],
    ["https://www.amazon.com/dp/B07D6FYHSK", "Product of Metamucil"],
    ["https://www.amazon.com/dp/B004GMC2N6", "Metamucil"],
    ["https://www.amazon.com/dp/B0077STR16", "Metamucil Generic"],
    ["https://www.amazon.com/dp/B000052Y5Q", "Metamucil"],
    ["https://www.amazon.com/dp/B00GCICW6O", ""],
    ["https://www.amazon.com/dp/B000XEEFTK", "Metamucil"],
    ["https://www.amazon.com/dp/B0077SXI7A", "Kirkland Signature"],
    ["https://www.amazon.com/dp/B00G4EH5AY", "Metamucil"],
    ["https://www.amazon.com/dp/B01CLIZH2Y", "Metamucil"],
    ["https://www.amazon.com/dp/B001G7QVAE", "Metamucil"],
    ["https://www.amazon.com/dp/B018OS3YIE", ""],
    ["https://www.amazon.com/dp/B001EP3IEA", ""],
    ["https://www.amazon.com/dp/B00THDTG7E", "NOW Foods"],
    ["https://www.amazon.com/dp/B003EX827I", "NOW Foods"],
    ["https://www.amazon.com/dp/B001EQ92VW", "NOW Foods"],
    ["https://www.amazon.com/dp/B00TIS57MG", "NOW Foods"],
    ["https://www.amazon.com/dp/B011D2QPF2", "NOW Foods"],
    ["https://www.amazon.com/dp/B00GQVA5YS", "NOW Foods"],
    ["https://www.amazon.com/dp/B0182R8PS6", "NOW Foods"],
    ["https://www.amazon.com/dp/B00SJKPBNY", "NOW Foods"],
    ["https://www.amazon.com/dp/B0159BINU8", "NOW Foods"],
    ["https://www.amazon.com/dp/B000JLIHAU", "NOW Foods"],
    ["https://www.amazon.com/dp/B002EA99HE", "NOW Foods"],
    ["https://www.amazon.com/dp/B00ZDWLTH8", "NOW Foods"],
    ["https://www.amazon.com/dp/B06XP5ZNZ2", "NOW Foods"],
    ["https://www.amazon.com/dp/B01LQEFFM6", "NOW Foods"],
    ["https://www.amazon.com/dp/B0159HV3PO", "NOW Foods"],
    ["https://www.amazon.com/dp/B00GQVA4VW", "NOW Foods"],
    ["https://www.amazon.com/dp/B000GQP7W4", "NOW Foods"],
    ["https://www.amazon.com/dp/B00RPKG0D4", "Now Foods"],
    ["https://www.amazon.com/dp/B0017WG1J4", "NOW Foods"],
    ["https://www.amazon.com/dp/B00L1GHMN0", "NOW Foods"],
    ["https://www.amazon.com/dp/B00D5YHZRE", "NOW Foods"],
    ["https://www.amazon.com/dp/B00GWZ0AWU", "NOW Foods"],
    ["https://www.amazon.com/dp/B0013OXKHC", "NOW Foods"],
    ["https://www.amazon.com/dp/B003PGCUKO", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B000YC70XY", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B003PGAO6Q", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B003XNCHAM", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B003PGCU4A", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B003PGANQ2", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B00BGVLG64", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B0016AXN7A", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B003PGAOYS", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B000VDP13M", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B003XN6XLQ", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B003PGFSW6", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B0075IXM3M", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B003PG6OQA", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B003PGAOD4", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B003XNCHD4", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B003PG6OMO", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B004LL58OC", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B00JDOAKRM", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B01L2UG4KQ", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B01M11KMUJ", "Organic India"],
    ["https://www.amazon.com/dp/B00CBECA8S", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B01MYE1UV1", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B0002BBATC", "Himalaya Herbal Healthcare"],
    ["https://www.amazon.com/dp/B00JJIF1US", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B0016A63CC", "Herb Pharm"],
    ["https://www.amazon.com/dp/B01L2UG57S", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B00WDEAZTW", "BRI Nutrition"],
    ["https://www.amazon.com/dp/B0041YRZ4K", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B01BJY5IS4", "Gina's Soft Cloth Shop"],
    ["https://www.amazon.com/dp/B01JH0M9PW", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B017JHU7HC", "True Veda"],
    ["https://www.amazon.com/dp/B00GDIJEPA", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/1609382773", ""],
    ["https://www.amazon.com/dp/B06ZYHJYD5", "NaturaLife Labs"],
    ["https://www.amazon.com/dp/B01JEEMTDS", ""],
    ["https://www.amazon.com/dp/B07GL26DHL", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B016MS4HDO", "Krishna Mart India"],
    ["https://www.amazon.com/dp/B07C5VLYJX", ""],
    ["https://www.amazon.com/dp/B000VDN1B6", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B079NMSPBW", "Physician's Choice"],
    ["https://www.amazon.com/dp/B00LMBBG7W", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/5856555252", ""],
    ["https://www.amazon.com/dp/B00I081JNQ", "LES Labs"],
    ["https://www.amazon.com/dp/B001F51MEM", ""],
    ["https://www.amazon.com/dp/B00AEJXP86", "ORGANIC INDIA"],
    ["https://www.amazon.com/dp/B00DIG9YIM", ""],
    ["https://www.amazon.com/dp/B005P0GTQY", "Planetary Formulas"],
    ["https://www.amazon.com/dp/B01HEDHBXY", "Sathiya Subramaniam"],
    ["https://www.amazon.com/dp/B00FPNZBVA", "Renew Life"],
    ["https://www.amazon.com/dp/B00CCCNISU", "Renew Life"],
    ["https://www.amazon.com/dp/B00IN7867Q", "Renew Life"],
    ["https://www.amazon.com/dp/B0042KULCG", "Renew Life"],
    ["https://www.amazon.com/dp/B0015R3L5S", "Renew Life"],
    ["https://www.amazon.com/dp/B009PGZX52", "Renew Life"],
    ["https://www.amazon.com/dp/B00KNX8LVY", "Renew Life"],
    ["https://www.amazon.com/dp/B004ZNDFIW", "Renew Life"],
    ["https://www.amazon.com/dp/B00FPNZCZU", "Renew Life"],
    ["https://www.amazon.com/dp/B0015R78DO", "Renew Life"],
    ["https://www.amazon.com/dp/B0047CTBS4", "Renew Life"],
    ["https://www.amazon.com/dp/B007XELFX2", "Renew Life"],
    ["https://www.amazon.com/dp/B0015R9EAY", "Renew Life"],
    ["https://www.amazon.com/dp/B0042L1S1S", "Renew Life"],
    ["https://www.amazon.com/dp/B0015R9DS2", "Renew Life"],
    ["https://www.amazon.com/dp/B0011G0DP4", "Renew Life"],
    ["https://www.amazon.com/dp/B003QAXJ1I", "Renew Life"],
    ["https://www.amazon.com/dp/B0047CV5K6", "Renew Life"],
    ["https://www.amazon.com/dp/B00014D1QK", "Renew Life"],
    ["https://www.amazon.com/dp/B00E0NDTP6", "Renew Life"],
    ["https://www.amazon.com/dp/B00OV28FXW", "Renew Life"],
    ["https://www.amazon.com/dp/B0015R9DD2", "Renew Life"],
    ["https://www.amazon.com/dp/B00PCL3KKE", "Renew Life"],
    ["https://www.amazon.com/dp/B01ATPBE6O", "Yerba Prima"],
    ["https://www.amazon.com/dp/B07743LDYM", "Yerba Prima"],
    ["https://www.amazon.com/dp/B01MTQLS8I", ""],
    ["https://www.amazon.com/dp/B00013Z128", "Yerba Prima"],
    ["https://www.amazon.com/dp/B000IRLIKG", "Yerba Prima"],
    ["https://www.amazon.com/dp/B000QYBMUC", "Yerba Prima"],
    ["https://www.amazon.com/dp/B001E0XFHK", "Yerba Prima"],
    ["https://www.amazon.com/dp/B000264L9I", "Yerba Prima"],
    ["https://www.amazon.com/dp/B0013JX59U", "Yerba Prima"],
    ["https://www.amazon.com/dp/B001E14OQA", "Yerba Prima"],
    ["https://www.amazon.com/dp/B00DGDC5LK", "Yerba Prima"],
    ["https://www.amazon.com/dp/B000F4SX1E", "Yerba Prima"],
    ["https://www.amazon.com/dp/B00024D5IS", "Yerba Prima"],
    ["https://www.amazon.com/dp/B01NBAL2TZ", "Yerba Prima"],
    ["https://www.amazon.com/dp/B005UO7U1S", "Yerba Prima"],
    ["https://www.amazon.com/dp/B00424VPZ4", "Yerba Prima"],
    ["https://www.amazon.com/dp/B00QSEJ7GU", "Yerba Prima"],
    ["https://www.amazon.com/dp/B0719MKMW5", "Guardian"],
    ["https://www.amazon.com/dp/B07HKJH7SB", "Yerba Prima"],
    ["https://www.amazon.com/dp/B000Z90KFG", "Yerba Prima"],
    ["https://www.amazon.com/dp/B001E0ZFUK", "Yerba Prima"],
    ["https://www.amazon.com/dp/B001E1AZH2", "Yerba Prima"],
    ["https://www.amazon.com/dp/B00014G38S", "Yerba Prima"],
]
ddd = {}
for e in ar:
    ddd[e[0]] = e[1]

config = {
    'com': {}
}
for e in p:
    try:
        title, url = e.split("@@")
        brand = ddd.get(url, "")

        prev_data = config['com'].get(brand, {})

        prev_data[title] = {
            'reviews': review_extract.get_review(url, title),
            'questions': get_questions(url),
            'url': url
        }
        config['com'][brand] = prev_data

    except Exception as e:
        print("Error", e)
        print(title)
        print(url)

file_name = "{}.json".format('com_quest')

import json

f = open(file_name, "w+")
f.write(json.dumps(config))
